name: Install Webserver Nginx

on:
  push:
    branches: ["main"]
  workflow_dispatch:
env:
    # Declarando variável no escopo do Workflow
    ENV_WORKFLOW: "RWA Workflow"
jobs:
    INSTALL-NGINX:
      runs-on: ubuntu-latest
      env:
        # Declarando variável no escopo do Job
        ENV_JOB: "RWA JOB"
      steps:
        - name: "Instalando o Webserver Nginx"
          env: 
            # Declarando variável no escopo da Action
            ENV_ACTION: "RWA ACTION"
          run: |
            sudo apt update --yes
            sudo apt install nginx --yes
            sudo nginx -v

            echo "Imprime variável no escopo da Action"
            echo "----------------------------------------"
            echo "Variável no esco da ACTION: $ENV_ACTION"

        - name: "Imprime os valores das variáveis"
          run: |
            echo "Imprime as varíavies no diversos escopos"
            echo "----------------------------------------"

            echo "Variável no escopo do Workflow: $ENV_WORKFLOW"
            echo "Variável no escopo do JOB: $ENV_JOB"
            echo "Variável no esco da ACTION: $ENV_ACTION"

            echo "----------------------------------------"

            echo "Imprime as varíavies de ambiente padrão GITHUB"
            echo "----------------------------------------"

            echo "Imprime nome da Action: $GITHUB_ACTION"
            echo "Imprime o Path do Repositório: $GITHUB_ACTION_PATH"
            echo "Imprime o Owner do Repositório: $GITHUB_ACTION_REPOSITORY"
            echo "Imprime qual o tipo de Runner: $GITHUB_ACTIONS"
            echo "Imprime o nome do Autor: $GITHUB_ACTOR"
            echo "Imprime o ID do Autor: $GITHUB_ACTOR_ID"
            echo "Imprime a API URL da: $GITHUB_API_URL"
            echo "Imprime qual a Branche: $GITHUB_BASE_REF"
            echo "Imprime path da variáveis runners: $GITHUB_ENV"
            echo "Imprime o método do start da Action: $GITHUB_EVENT_NAME"
            
        

